#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import

import sys
from PySide6 import QtWidgets
from argus_gui import Logger

"""
log.py - Called by all Argus GUIs to display the progress and errors of any Argus operation.  Not intended for users directly.  If you want to take advantage of argus_gui's logging abilities,
use the class Logger directly.
"""

if __name__ == '__main__':
    # parses through the passed arguments for the command and options
    cmd = sys.argv[1:]

    # are we going to write a log?
    if cmd[0] == 'True':
        write = True
    else:
        write = False

    # temporary directory
    tmp = cmd[1]
    # actual command to run and display its stdout and stderr
    cmd = cmd[2:]

    # start doing stuff
    app = QtWidgets.QApplication.instance()
    if app is None:
        app = QtWidgets.QApplication(sys.argv)
    log = Logger(cmd, tmp=tmp, wLog=write)
    log.update_log()
    log.loop.exec()
    # log.show()
    # app.exec()

