#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Author: Dylan Ray
# rebuilt by Brandon E. Jackson 20230601

from PySide6 import QtGui, QtWidgets, QtCore
from argus_gui import Argus

if __name__ == '__main__':
    app = QtWidgets.QApplication()
    window = Argus.MainWindow(app)
    window.show()
    app.exec()